readme update

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -31,21 +31,28 @@ before_script:
     fi
 
 script:
-  # Create swarm for explicit testing
-  # Make sure that there is a useable ip address as "advertise address" because else the swarm creation fails maybe
-  - docker swarm init --advertise-addr `ip addr s | grep global | grep -oE '((1?[0-9][0-9]?|2[0-4][0-9]|25[0-5])\.){3}(1?[0-9][0-9]?|2[0-4][0-9]|25[0-5])' | head -n1`
+    # Create swarm for explicit testing
+    # Make sure that there is a useable ip address as "advertise address" because else the swarm creation fails maybe
+    # docker swarm init --advertise-addr `ip addr s | grep global | grep -oE '((1?[0-9][0-9]?|2[0-4][0-9]|25[0-5])\.){3}(1?[0-9][0-9]?|2[0-4][0-9]|25[0-5])' | head -n1`
   - docker build -t "$THIS_IMAGE" .
+  # = - = - = - = - = - = - = - = - = - = - = - = - = - = - = - = - = - = - =
   - docker run -d --name "$CONTAINER_NAME" -p 2368:2368 -e url=http://localhost:2368 -e NODE_ENV=production "$THIS_IMAGE"
+  - echo "Wait for $CONTAINER_NAME to be available..."
   - until $(curl --output /dev/null --silent --head --fail http://localhost:2368); do
-        echo "Waiting for $CONTAINER_NAME container to run...";
-        sleep 3;
+      echo "Waiting for $CONTAINER_NAME container to run...";
+      sleep 3;
     done
-  - echo "$CONTAINER_NAME is available..."
+  # = - = - = - = - = - = - = - = - = - = - = - = - = - = - = - = - = - = - =
   - curl http://localhost:2368 | grep "The professional publishing platform"
+  # = - = - = - = - = - = - = - = - = - = - = - = - = - = - = - = - = - = - =
   - echo "Time to run official docker test on the container..."
   - ~/official-images/test/run.sh "$THIS_IMAGE"
-  - echo "--- TEST 01 ---";
-  - uname -a;
+  # = - = - = - = - = - = - = - = - = - = - = - = - = - = - = - = - = - = - =
+  - echo "--- TEST 01 ---" && uname -a;
+  - echo "--- TEST 02 ---" && node --version;
+  - echo "--- TEST 03 ---" && cat /var/lib/ghost/current/content/themes/casper/package.json | grep version;
+  - echo "--- TEST 04 ---" && cat /var/lib/ghost/current/package.json | grep version;
+  - echo "--- TEST 05 ---" && curl -Is --head "http://localhost:2368" | grep -F -o "HTTP/1.1 200 OK" || echo "Error --> http://localhost:2368";
 
 after_script:
   - docker inspect "$THIS_IMAGE";
@@ -63,4 +70,4 @@ after_success:
   - if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" == "master" ] && [ "$DOCKER_REPO_PREFIX" != "" ] && [ "$DOCKER_REPO_NAME" != "" ] && [ "$DOCKER_USERNAME" != "" ] && [ "$DOCKER_PASSWORD" != "" ]; then
       echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin;
       docker push "$THIS_IMAGE";
-      fi
+    fi
