Travis / Better tagging and better unit tests /A

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -7,7 +7,7 @@ services:
 # TODO - Hook the VAR from ./build-config.sh
 env:
   global:
-    - GHOST_VERSION="1.22.4B"
+    - GHOST_VERSION="1.22.4C"
 
 before_install:
   - docker --version
@@ -26,10 +26,12 @@ install:
 before_script:
   - CONTAINER_NAME="ghostuat"
   - THIS_DATE=$(date -u +"%Y-%m-%d_%H-%M-%S")
-  - THIS_SHA=$(git log -1 | head -1 | awk '{print $2}')
+  - THIS_SHA_LONG=$(git log -1 | head -1 | awk '{print $2}')
+  - THIS_SHA_SHORT=$(git rev-parse --short HEAD)
   - IMAGE_VERSION="$DOCKER_USERNAME"/"$DOCKER_REPO_NAME":"$GHOST_VERSION"
   - IMAGE_DATE="$DOCKER_USERNAME"/"$DOCKER_REPO_NAME":"$THIS_DATE"
-  - IMAGE_SHA="$DOCKER_USERNAME"/"$DOCKER_REPO_NAME":"$THIS_SHA"
+  - IMAGE_SHA_LONG="$DOCKER_USERNAME"/"$DOCKER_REPO_NAME":"$THIS_SHA_LONG"
+  - IMAGE_SHA_SHORT="$DOCKER_USERNAME"/"$DOCKER_REPO_NAME":"$GHOST_VERSION"-"$THIS_SHA_SHORT"
   - if [ -n "$TRAVIS_TAG" ]; then
     image="$image:$TRAVIS_TAG";
     fi
@@ -38,8 +40,8 @@ script:
     # Make sure that there is a useable ip address as "advertise address" because else the swarm creation fails maybe
     # docker swarm init --advertise-addr `ip addr s | grep global | grep -oE '((1?[0-9][0-9]?|2[0-4][0-9]|25[0-5])\.){3}(1?[0-9][0-9]?|2[0-4][0-9]|25[0-5])' | head -n1`
   # Building with 3 TAGS
-  - docker build -t "$IMAGE_SHA" .
-  - docker run -d --name "$CONTAINER_NAME" -p 2368:2368 -e url=http://localhost:2368 -e NODE_ENV=production "$IMAGE_SHA"
+  - docker build -t "$IMAGE_SHA_LONG" .
+  - docker run -d --name "$CONTAINER_NAME" -p 2368:2368 -e url=http://localhost:2368 -e NODE_ENV=production "$IMAGE_SHA_LONG"
   - echo "Ensure $CONTAINER_NAME is starting..."
   - until $(curl --output /dev/null --silent --head --fail http://localhost:2368); do
       echo "Waiting for $CONTAINER_NAME container to run...";
@@ -47,7 +49,7 @@ script:
     done
   - curl http://localhost:2368 | grep "The professional publishing platform"
   - echo "Time to run official docker test on the container..."
-  - ~/official-images/test/run.sh "$IMAGE_SHA"
+  - ~/official-images/test/run.sh "$IMAGE_SHA_LONG"
   - uname -a;
 
 after_script:
@@ -55,26 +57,38 @@ after_script:
   - docker images;
   - docker logs "$CONTAINER_NAME";
   - echo "Starting unit tests "
-  - docker exec -it $CONTAINER_NAME uname -a;
-  - docker exec -it $CONTAINER_NAME node --version;
-  - docker exec -it $CONTAINER_NAME cat /var/lib/ghost/current/content/themes/casper/package.json | grep version;
-  - docker exec -it $CONTAINER_NAME cat /var/lib/ghost/current/package.json | grep version;
-  - docker exec -it $CONTAINER_NAME curl -Is --head "http://localhost:2368" | grep -F -o "HTTP/1.1 200 OK" || echo "Error --> http://localhost:2368"
+  - docker exec -it "$CONTAINER_NAME" uname -a;
+  - docker exec -it "$CONTAINER_NAME" node --version;
+  - docker exec -it "$CONTAINER_NAME" cat /var/lib/ghost/current/content/themes/casper/package.json | grep version;
+  - docker exec -it "$CONTAINER_NAME" cat /var/lib/ghost/current/package.json | grep version;
+  - docker exec -it "$CONTAINER_NAME" curl -Is --head "http://localhost:2368" | grep -F -o "HTTP/1.1 200 OK" || echo "Error --> http://localhost:2368"
   - docker rm -f "$CONTAINER_NAME";
+  - echo
+  - echo "IMAGE_SHA_SHORT=$IMAGE_SHA_SHORT"
+  - echo "IMAGE_VERSION=$IMAGE_VERSION"
+  - echo "IMAGE_SHA_LONG=$IMAGE_SHA_LONG"
+  - echo "IMAGE_DATE=$IMAGE_DATE"
+  - echo "#IMAGE_SHA_SHORT=$IMAGE_SHA_SHORT"
+  - echo "#IMAGE_VERSION=$IMAGE_VERSION"
+  - echo "#IMAGE_SHA_LONG=$IMAGE_SHA_LONG"
+  - echo "#IMAGE_DATE=$IMAGE_DATE"
 
 after_success:
+      #docker build -t "$IMAGE_SHA_LONG" (already built)
   - if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" == "master" ] && [ "$DOCKER_REPO_PREFIX" != "" ] && [ "$DOCKER_REPO_NAME" != "" ] && [ "$DOCKER_USERNAME" != "" ] && [ "$DOCKER_PASSWORD" != "" ]; then
       echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin;
-      docker push "$IMAGE_SHA";
+      docker push "IMAGE_SHA_LONG";
       docker build -t "$IMAGE_VERSION" .;
       docker push "$IMAGE_VERSION";
       docker build -t "$IMAGE_DATE" .;
       docker push "$IMAGE_DATE";
+      docker build -t "$IMAGE_SHA_SHORT" .;
+      docker push "$IMAGE_SHA_SHORT";
     fi
 
   # See https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings
 
-  # VAR managed by Travis:
+  # Secret VARS managed by Travis:
     # DOCKER_USERNAME=[secure]
     # DOCKER_PASSWORD=[secure]
     # DOCKER_REPO_PREFIX=[secure]
